### ISSUE TITLE
HTML too small when put on a screen

### ISSUE THREAD

**Issue by MichaelGoulding** [Catharius/DU-MINIMALIST-HUD#1]
How can one get it stretched to fit a screen?

Thanks so much!

**Comment by Catharius** [comment]
Hello, for now i have an issue with screens (if there is too much elements, we reach the limit of characters).  If your screen is not showing the red error message it means it is still OK.

You can use the following lua parameters : 
- damagereport_ratio_modifier : Use this to scale up or down the ship layout
- Use damagereport_x_pos_modifier and damagereport_y_pos_modifier to adjust and center it on your screen

**Comment by Catharius** [comment]
Hello, i have released a screen version that should do the trick. https://github.com/Catharius/DU-SIMPLE-DAMAGE-REPORT
