### ISSUE TITLE
Suggestion:  Damage Location Rendered to Screen

### ISSUE THREAD

**Issue by timbrown81** [Catharius/DU-MINIMALIST-HUD#2]
I love the element display aspect of your HUD.  Have you considered making the damage location portion standalone for display on a screen?  This would be useful and look great on a bridge display.

**Comment by Catharius** [comment]
Hello, that is a good idea. I will see what i can do about it. First i need to improve how the damage location is rendered so it can be moved and scaled properly to fit the screen.

**Comment by Catharius** [comment]
Hello, you should check this script for the screen version https://github.com/Catharius/DU-SIMPLE-DAMAGE-REPORT.
